from __future__ import annotations

import json
import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from .config import Language
from .schema import Challenge


WRITEUP_NAME = "writeup.md"
DEFAULT_SOLVE_NAME = "solve.py"
SCRIPT_CANDIDATE_NAMES = (
    "solve.py",
    "solve.sage",
    "solve.sage.py",
    "exploit.py",
    "solve.sh",
    "exploit.sh",
)


@dataclass
class SuccessArtifacts:
    writeup_path: Path
    solve_path: Path


def write_success_artifacts(
    *,
    challenge_dir: Path,
    run_dir: Path,
    challenge: Challenge,
    flag: str,
    language: Language,
) -> SuccessArtifacts:
    challenge_dir = challenge_dir.resolve()
    writeup_path = challenge_dir / WRITEUP_NAME
    solve_path = write_solve_artifact(challenge_dir=challenge_dir, run_dir=run_dir, flag=flag, language=language)
    writeup_path.write_text(
        build_writeup(
            challenge_dir=challenge_dir,
            run_dir=run_dir,
            challenge=challenge,
            flag=flag,
            solve_path=solve_path,
            language=language,
        ),
        encoding="utf-8",
    )
    return SuccessArtifacts(writeup_path=writeup_path, solve_path=solve_path)


def write_solve_artifact(
    *,
    challenge_dir: Path,
    run_dir: Path,
    flag: str,
    language: Language,
) -> Path:
    source = find_solution_script(run_dir)
    if source is not None:
        target = challenge_dir / source.name
        text = source.read_text(encoding="utf-8", errors="replace")
        target.write_text(script_header(flag, language, source.suffix) + text, encoding="utf-8")
        return target

    command = find_reproduction_command(run_dir, flag)
    target = challenge_dir / DEFAULT_SOLVE_NAME
    target.write_text(build_fallback_solve(flag=flag, command=command, language=language), encoding="utf-8")
    return target


def find_solution_script(run_dir: Path) -> Path | None:
    work_dir = run_dir / "work"
    if not work_dir.exists():
        return None
    candidates: list[Path] = []
    for name in SCRIPT_CANDIDATE_NAMES:
        candidates.extend(path for path in work_dir.rglob(name) if path.is_file())
    if not candidates:
        candidates.extend(
            path
            for path in work_dir.rglob("*")
            if path.is_file()
            and path.suffix in {".py", ".sage", ".sh"}
            and path.name not in {"task.py", "server.py", "chall.py"}
        )
    if not candidates:
        return None
    priority = {name: index for index, name in enumerate(SCRIPT_CANDIDATE_NAMES)}
    return sorted(
        candidates,
        key=lambda path: (
            priority.get(path.name, len(priority)),
            len(path.parts),
            path.name,
        ),
    )[0]


def script_header(flag: str, language: Language, suffix: str) -> str:
    if suffix not in {".py", ".sage", ".sh"}:
        return ""
    if language == "zh":
        return (
            f"# 由 ai-ctfer 在解题成功后整理。\n"
            f"# 最终 flag: {flag}\n"
            "# 详细过程见 writeup.md。\n\n"
        )
    return (
        "# Organized by ai-ctfer after a successful solve.\n"
        f"# Final flag: {flag}\n"
        "# See writeup.md for the detailed process.\n\n"
    )


def build_fallback_solve(*, flag: str, command: str | None, language: Language) -> str:
    if language == "zh":
        intro = (
            "#!/usr/bin/env python3\n"
            "# 由 ai-ctfer 在解题成功后生成。\n"
            f"# 最终 flag: {flag}\n"
            "# 未在运行工作区中找到独立 solve/exploit 脚本，因此此脚本保存最终结果，\n"
            "# 并在可能时重放产生 flag 的命令。详细过程见 writeup.md。\n"
        )
        no_command = "# 没有找到可安全重放的单条命令，直接输出最终 flag。\n"
    else:
        intro = (
            "#!/usr/bin/env python3\n"
            "# Generated by ai-ctfer after a successful solve.\n"
            f"# Final flag: {flag}\n"
            "# No standalone solve/exploit script was found in the run workspace, so this\n"
            "# script preserves the final result and replays the producing command if one\n"
            "# was available. See writeup.md for the detailed process.\n"
        )
        no_command = "# No safe single-command replay was found; print the final flag.\n"

    if command:
        return (
            intro
            + "\nimport subprocess\n\n"
            + f"COMMAND = {command!r}\n"
            + f"FLAG = {flag!r}\n\n"
            + "def main() -> None:\n"
            + "    completed = subprocess.run(COMMAND, shell=True, text=True, capture_output=True, check=False)\n"
            + "    if completed.stdout:\n"
            + "        print(completed.stdout, end='')\n"
            + "    if completed.stderr:\n"
            + "        print(completed.stderr, end='')\n"
            + "    if FLAG not in completed.stdout and FLAG not in completed.stderr:\n"
            + "        print(FLAG)\n\n"
            + "if __name__ == '__main__':\n"
            + "    main()\n"
        )

    return (
        intro
        + "\n"
        + no_command
        + f"FLAG = {flag!r}\n\n"
        + "def main() -> None:\n"
        + "    print(FLAG)\n\n"
        + "if __name__ == '__main__':\n"
        + "    main()\n"
    )


def build_writeup(
    *,
    challenge_dir: Path,
    run_dir: Path,
    challenge: Challenge,
    flag: str,
    solve_path: Path,
    language: Language,
) -> str:
    trace_events = load_trace_events(run_dir)
    plan = read_text(run_dir / "plan.md")
    summary = read_text(run_dir / "summary.md")
    candidate_log = read_text(run_dir / "flag_candidates.jsonl")
    run_duration = summarize_run_duration(trace_events, language)
    commands = summarize_commands(trace_events, language)
    candidate_summary = summarize_candidates(candidate_log)
    failed_attempts = summarize_failed_attempts(trace_events, candidate_log, language)

    if language == "zh":
        return "\n".join(
            [
                f"# {challenge.display_name} Writeup",
                "",
                "## 结果",
                "",
                f"- Flag: `{flag}`",
                f"- 类别：`{challenge.category.value}`",
                f"- 解题脚本：`{solve_path.name}`",
                f"- 耗时：{run_duration}",
                "",
                "## 题目信息",
                "",
                code_block(challenge.description or "（无 description）", "text"),
                "",
                "## 解题计划",
                "",
                plan or "（没有保存计划）",
                "",
                "## 关键尝试与结果",
                "",
                commands or "（没有可汇总的命令记录）",
                "",
                "## Flag 候选与校验",
                "",
                candidate_summary or "（没有候选日志）",
                "",
                "## 运行摘要",
                "",
                summary or "（没有 summary）",
                "",
                "## 失败尝试简记",
                "",
                failed_attempts or "（没有明显失败尝试）",
                "",
            ]
        )

    return "\n".join(
        [
            f"# {challenge.display_name} Writeup",
            "",
            "## Result",
            "",
            f"- Flag: `{flag}`",
            f"- Category: `{challenge.category.value}`",
            f"- Solve script: `{solve_path.name}`",
            f"- Elapsed: {run_duration}",
            "",
            "## Challenge Information",
            "",
            code_block(challenge.description or "(no description)", "text"),
            "",
            "## Solve Plan",
            "",
            plan or "(no saved plan)",
            "",
            "## Key Attempts And Results",
            "",
            commands or "(no command records to summarize)",
            "",
            "## Flag Candidates And Validation",
            "",
            candidate_summary or "(no candidate log)",
            "",
            "## Run Summary",
            "",
            summary or "(no summary)",
            "",
            "## Brief Failed Attempts",
            "",
            failed_attempts or "(no obvious failed attempts)",
            "",
        ]
    )


def summarize_run_duration(events: list[dict[str, object]], language: Language) -> str:
    timestamps = [
        parsed
        for event in events
        if (parsed := parse_timestamp(event.get("ts"))) is not None
    ]
    if len(timestamps) < 2:
        return "未知" if language == "zh" else "unknown"

    start = timestamps[0]
    end = None
    for event in reversed(events):
        if event.get("event") == "success":
            end = parse_timestamp(event.get("ts"))
            if end is not None:
                break
    if end is None:
        end = timestamps[-1]

    elapsed = max(0, int(round((end - start).total_seconds())))
    return format_duration(elapsed, language)


def parse_timestamp(value: object) -> datetime | None:
    if not isinstance(value, str) or not value.strip():
        return None
    try:
        return datetime.fromisoformat(value)
    except ValueError:
        return None


def format_duration(total_seconds: int, language: Language) -> str:
    hours, remainder = divmod(total_seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    if language == "zh":
        parts = []
        if hours:
            parts.append(f"{hours} 小时")
        if minutes:
            parts.append(f"{minutes} 分钟")
        if seconds or not parts:
            parts.append(f"{seconds} 秒")
        return " ".join(parts)
    if hours:
        return f"{hours}h {minutes}m {seconds}s"
    if minutes:
        return f"{minutes}m {seconds}s"
    return f"{seconds}s"


def find_reproduction_command(run_dir: Path, flag: str) -> str | None:
    for event in reversed(load_trace_events(run_dir)):
        if event.get("event") not in {"command_result", "planning_command_result"}:
            continue
        result = event.get("result") or {}
        output = f"{result.get('stdout', '')}\n{result.get('stderr', '')}"
        if flag in output:
            action = event.get("action") or {}
            command = action.get("command") or result.get("command")
            if isinstance(command, str) and command.strip():
                return command
    return None


def summarize_commands(events: list[dict[str, object]], language: Language, max_items: int = 30) -> str:
    lines: list[str] = []
    for event in events:
        if event.get("event") not in {"command_result", "planning_command_result"}:
            continue
        action = event.get("action") if isinstance(event.get("action"), dict) else {}
        result = event.get("result") if isinstance(event.get("result"), dict) else {}
        command = str(action.get("command") or result.get("command") or "")
        rationale = str(action.get("rationale") or "")
        stdout = str(result.get("stdout") or "").strip()
        stderr = str(result.get("stderr") or "").strip()
        exit_code = result.get("exit_code")
        if language == "zh":
            lines.append(f"- 意图：{rationale or '（无）'}")
            lines.append(f"  - 命令：`{shorten(command, 220)}`")
            lines.append(f"  - 结果：exit={exit_code}")
        else:
            lines.append(f"- Intent: {rationale or '(none)'}")
            lines.append(f"  - Command: `{shorten(command, 220)}`")
            lines.append(f"  - Result: exit={exit_code}")
        excerpt = shorten(stdout or stderr, 500)
        if excerpt:
            label = "输出摘录" if language == "zh" else "Output excerpt"
            lines.append(f"  - {label}: `{escape_backticks(excerpt)}`")
        if len([line for line in lines if line.startswith("- ")]) >= max_items:
            break
    return "\n".join(lines)


def summarize_candidates(candidate_log: str) -> str:
    if not candidate_log.strip():
        return ""
    lines: list[str] = []
    for raw in candidate_log.splitlines()[-20:]:
        try:
            record = json.loads(raw)
        except json.JSONDecodeError:
            continue
        candidate = record.get("candidate") or {}
        if not isinstance(candidate, dict):
            continue
        value = candidate.get("value")
        status = candidate.get("status")
        confidence = candidate.get("confidence")
        source = candidate.get("source")
        event = record.get("event")
        lines.append(f"- `{value}` event={event} status={status} confidence={confidence} source={source}")
    return "\n".join(lines)


def summarize_failed_attempts(
    events: list[dict[str, object]],
    candidate_log: str,
    language: Language,
    max_items: int = 10,
) -> str:
    items: list[str] = []
    for event in events:
        if event.get("event") not in {"command_result", "planning_command_result", "command_skipped"}:
            continue
        action = event.get("action") if isinstance(event.get("action"), dict) else {}
        result = event.get("result") if isinstance(event.get("result"), dict) else {}
        command = str(action.get("command") or result.get("command") or event.get("command") or "")
        rationale = str(action.get("rationale") or event.get("rationale") or "")
        reason = failed_event_reason(event, result, language)
        if not reason:
            continue
        if language == "zh":
            items.append(f"- {reason}：{rationale or shorten(command, 160)}")
        else:
            items.append(f"- {reason}: {rationale or shorten(command, 160)}")
        if len(items) >= max_items:
            break

    for raw in candidate_log.splitlines():
        if len(items) >= max_items:
            break
        try:
            record = json.loads(raw)
        except json.JSONDecodeError:
            continue
        if record.get("event") != "candidate_rejected":
            continue
        candidate = record.get("candidate") or {}
        if not isinstance(candidate, dict):
            continue
        value = candidate.get("value")
        reasons = candidate.get("reasons") or []
        reason = str(reasons[-1]) if reasons else "candidate rejected"
        if language == "zh":
            items.append(f"- 拒绝候选 `{value}`：{shorten(reason, 220)}")
        else:
            items.append(f"- Rejected candidate `{value}`: {shorten(reason, 220)}")

    return "\n".join(items)


def failed_event_reason(event: dict[str, object], result: dict[str, object], language: Language) -> str | None:
    zh = language == "zh"
    if event.get("event") == "command_skipped":
        return "跳过重复命令" if zh else "skipped repeated command"
    if result.get("timed_out"):
        return "命令超时" if zh else "command timed out"
    exit_code = result.get("exit_code")
    if isinstance(exit_code, int) and exit_code != 0:
        return f"命令退出码 {exit_code}" if zh else f"command exited with {exit_code}"
    output = f"{result.get('stdout', '')}\n{result.get('stderr', '')}".lower()
    if re.search(r"\b(?:http/\S+\s+)?404\b", output) or "not found" in output:
        return "目标路径不存在或返回 404" if zh else "target path missing or returned 404"
    if "missing" in output or "warning" in output:
        return "输出提示缺少信息" if zh else "output indicated missing information"
    if "connection refused" in output or "failed to connect" in output:
        return "连接失败" if zh else "connection failed"
    return None


def load_trace_events(run_dir: Path) -> list[dict[str, object]]:
    path = run_dir / "trace.jsonl"
    if not path.exists():
        return []
    events: list[dict[str, object]] = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        try:
            raw = json.loads(line)
        except json.JSONDecodeError:
            continue
        if isinstance(raw, dict):
            events.append(raw)
    return events


def read_text(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="replace").strip()


def code_block(text: str, language: str = "") -> str:
    return f"```{language}\n{text.strip()}\n```"


def truncate_markdown(text: str, max_chars: int) -> str:
    text = text.strip()
    if len(text) <= max_chars:
        return text
    return text[: max_chars // 2].rstrip() + "\n\n...[truncated]...\n\n" + text[-max_chars // 2 :].lstrip()


def shorten(text: str, max_chars: int) -> str:
    text = " ".join(text.split())
    if len(text) <= max_chars:
        return escape_backticks(text)
    return escape_backticks(text[: max_chars - 3].rstrip() + "...")


def escape_backticks(text: str) -> str:
    return text.replace("`", "'")
